name: Sonar Analysis
on:
# can be used to run the workflow manually
  workflow_dispatch:
# the workflow will be trigger on a push on the specified branch/branches
  push:
    branches:
      - trunk
 
jobs:
  sonar:
    runs-on: java8
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Sonar Scanner
        run: |
          ./gradlew test jacocoTestReport sonarqube -Dsonar.projectKey=DWB-BE -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_DWB_BE_TOKEN }}
